.github/workflows/javascript-test.yml
README.md

Spliced the continuous testing step into three separated steps.
Added the yarn install as a needed step that downloads the dependencies (just to stop it from spamming three yarn installs at the same time).
Closes #7

Split CT into three steps

---

.eslintrc.cjs
package.json
yarn.lock

This removes the need to disable `no-restricted-imports`

updated linting to use latest version

---

src/file/validator.ts
src/runner.ts
src/test/runner/config.test.ts

Created method which validates the regex expressions in a configuration.
Closes #16
I want to have a constant error type + a custom error log so I make it return either a passed status or a failed status + error message so it can be logged.

Added regex validation

---

src/file/types.ts
src/file/validator.ts
src/runner.ts
src/test/runner/basicRule.test.ts
src/test/runner/config.test.ts

Created object for basic rule.
First step towards #9
By using Types in typescript we can differ what is the type of rule easily. I also added checks to Joi to ensure that the rule has everything required before individually validating it.
Added tests to evaluate the process thoroughly.

Created basic rule

---

action.yml
package.json
src/file/types.ts
src/github/pullRequest.ts
src/github/teams.ts
src/index.ts
src/runner.ts
src/test/runner/basicRule.test.ts
src/test/runner/conditions.test.ts
src/test/runner/config.test.ts
src/test/runner/runner.test.ts

Implemented the functionality of the basic rule.
Because every rule ends up being simplified into:
```typescript
{
min_approvals: number;
teams?: string[];
users?: string[];
}
```
I created a basic logic that evaluates that. After this, we can use the result of those smaller conditions to evaluate the more complex rules.
I added a lot of tests and tried to do as many comments to explain the logic as possible.
Created class which handles the teams token and obtains the team members of a team.
This class is small but handles the token used for such authentication and separates the concern. 
If we decide to replace GitHub teams for on-chain data (like mentioned in paritytech/opstooling#245) this would let us to simply switch the implementation with minimal alterations.
Closes #22 and closes …

Created BASIC rule implementation

---

src/runner.ts
src/test/runner/conditions.test.ts
yarn.lock

Added validation that the amount of available users must not be smaller than the amount of required reviews.
Closes #27
Also fixed a small security vulnerability in a dependency.

Handle not enough reviewers

---

src/file/validator.ts
src/runner.ts
src/test/runner/conditions.test.ts
src/util.ts

Fixed the `XOR` condition for a `OR` condition.
Updated tests.
Closes #28

Fixed user OR teams to users AND teams

---

.github/workflows/review-bot.yml
action.yml
src/file/validator.ts
src/github/pullRequest.ts
src/github/teams.ts
src/runner.ts
src/test/runner/basicRule.test.ts
src/test/runner/config.test.ts

Resolves #6 
This PR implements the GitHub action on itself (so we can test it every time!)
Until https://github.com/paritytech/internal_it/issues/205 is resolved, this PR should not be merged (and we need to update the keys and token generation step)
In the meanwhile, I added a temporary token (that expires in one week).
- Fixed validation of rules not setting default values.
- Fixed basic rule amount of review to be a positive integer (min value 1)
- Added a test to verify this
- Implemented GitHub Action to run on Pull Requests.
- Added a log which reports what teams and users are missing.
- Fixed a bug where the approvals wasn’t being properly filtered.
- Fixed a bug where the system asked the author to review the PR
- Fixed the wrong default name of the config file
- Was set to …

implemented action on itself

---

src/github/pullRequest.ts
src/util.ts

The system currently searches for approved reviews, but if a user approves a review, and then they reject the review, only the approval review takes this change into consideration.
This solves that problem and fixes #38

Fixed user's review not being taken in order

---

.github/workflows/publish.yml
.github/workflows/review-bot.yml

I had many times the problem of setting the action to point to its own branch to test, only to forget about setting it again to the main branch.
This adds a check that makes the PR fails unless that the branch is actually pointing to main.

added action validation

---

.github/workflows/review-bot.yml
src/github/pullRequest.ts
src/github/types.ts
src/index.ts
src/runner.ts

Added ability to generate a status check and the ability to overwrite the latest one.
This resolves #33 and closes #26 as it merged it into one ticket.
There are some limitations as we can not select the check suite that the check will belong (see https://github.com/paritytech/review-bot/issues/33#issuecomment-1662034503), but the name will be constant, making it validable.

Added status checks

---

.github/workflows/publish.yml
.github/workflows/review-bot.yml
src/github/pullRequest.ts
src/runner.ts

Now that https://github.com/paritytech/internal_it/issues/205 has been completed, this change removes my personal access token and replaces it for the GitHub App.

updated repo to use team github app

---

.github/workflows/publish.yml
src/rules/types.ts
src/rules/validator.ts
src/runner.ts
src/test/rules/config.test.ts
src/test/rules/or.test.ts
src/test/runner/validation/or.test.ts

Hello, and welcome to Javier's list of new changes. Today, we have a new feature: **The _OR_ rule**
- Created `OR` rule
- This resolves #12
- The OR rule verifies that *one* of the conditions have been fulfilled.
- When a condition was fulfilled, it continues the loop to the next rule
- Should this be a "break" instead?
- When the `OR` rule fails, it shows all the users it needs a review but it only shows the amount of missing reviews using the sub condition with the minimum amount of reviews needed.
- Created lots of test.
- This are mainly a copy and modification of `AND` as they share logic and structure.

Created 'OR' rule

---

.github/workflows/review-bot.yml
src/index.ts
src/runner.ts
src/test/runner/runner.test.ts
src/test/runner/validation/and.test.ts
src/test/runner/validation/or.test.ts

Added an output to the action.
It will return a stringified JSON of type:
```typescript
type PullRequestReport = {
/** List of files that were modified by the PR */
files: string[];
/** List of all the failed review requirements */
reports: {
/** The amount of missing reviews to fulfill the requirements */
missingReviews: number;
/** The users who would qualify to complete those reviews */
missingUsers: string[];
/** If applicable, the teams that should be requested to review */
teamsToRequest?: string[];
/** If applicable, the users that should be requested to review */
usersToRequest?: string[];
}[];
};
```
Resolves #17 and resolves #43

added output to action execution

---

.github/review-bot.yml
README.md
src/github/pullRequest.ts
src/rules/types.ts
src/rules/validator.ts
src/runner.ts
src/test/github.test.ts
src/test/rules/basicRule.test.ts
src/test/rules/or.test.ts
src/test/runner/validation/andDistinct.test.ts

Resolves #34
Created the option to count the author of a PR as an approval.
This has to be set per review option.
In the case of the "normal" rules it doesn't change the logic.
In the case of the "and-distinct" rule we have to decide if we filter the author from the PR on evaluation time.

Author as reviewer

---

README.md
src/rules/validator.ts
src/runner.ts
src/test/rules/config.test.ts
src/test/runner/runner.test.ts

Added the feature `Prevent review request`
Thie resolves #59.
It allows us to not request the review of some teams or users.
As we don't have the request review implementation yet (see #53), I didn't add any explanation in the README.

Prevent review request

---

.github/workflows/publish.yml
README.md
action.yml

Created deploy script to automatically deploy new versions to GitHub packages using Docker.
The deployment was copied from [stale-pr-finder/.github/workflows/publish.yml](https://github.com/paritytech/stale-pr-finder/blob/main/.github/workflows/publish.yml)
Closes #55

Automated deployment

---

README.md
src/rules/types.ts
src/rules/validator.ts
src/runner.ts
src/test/config.yml
src/test/index.test.ts
src/test/rules/config.test.ts
src/test/runner/runner.test.ts

This adds the feature to exclude rules from being executed when the author belongs to a particular team or list. 
This resolves #66.

Added excludeAuthors feature

---

src/runner.ts
src/test/runner/validation/andDistinct.test.ts

Found a bug where usernames where duplicated in the error object.
This fixes #73

Fixed duplicated usernames in and-distinct error object

---

action.yml
package.json
src/github/pullRequest.ts
src/github/teams.ts

Added more logs when fetching approvals and team members.
Removed a left over log
Now the debug logs will count the author and will show the team members (debug logs can only be seen by people who have access to trigger the actions)
Resolves #74
Updated version to `1.0.1`

Added more debug log verbosity

---

src/runner.ts
src/test/runner/conditions.test.ts
src/test/runner/validation/and.test.ts
src/test/runner/validation/andDistinct.test.ts
src/test/runner/validation/or.test.ts

Enhanced the check report, adding the information of the missing rank. This resolves #80 
Added tests that evaluate the ranking system, and how it applies the rules. This resolves #81
For the `or` rule, we request the lowest required rank, and for the `and` rule we request the highest rank.
In the case of `and-distinct` we request the highest rank.

Added better rank report and testing

---

.github/workflows/publish.yml

Implemented new CI method. This was copied directly from the [CI file from `auto-merge-bot`](https://github.com/paritytech/auto-merge-bot/blob/main/.github/workflows/release.yml)

updated CI to use `gh`

---

action.yml
package.json
src/github/teams.ts
src/test/index.test.ts
src/test/teams.test.ts

Fixed a pagination issue where the system was only obtaining the first 30 membes of a team.
By adding the [pagination method of Octokit](https://actions-cool.github.io/octokit-rest/guide/05_pagination/) we can obtain all of the results at once.
Updated project version to 2.0.1 to generate a new release.
This fixes #88

Fixed bug where only 30 members where shown

---

.github/workflows/publish.yml
.github/workflows/review-bot.yml
.github/workflows/review-trigger.yml
README.md
action.yml
package.json
src/github/pullRequest.ts
src/index.ts
src/test/github.test.ts
src/test/index.test.ts
yarn.lock

This allows is to fetch the PR directly instead of obtaining it from the event. It is an alternative solution for when we are using a dispatch event.
This resolves #93
This also allows the use of `environment` because every event is being triggered from the default branch.
I also updated dependencies.

added Pull Request number as input

---

README.md
action.yml
src/github/pullRequest.ts
src/index.ts
src/runner.ts
src/test/github.test.ts
src/test/runner/runner.test.ts

Added the feature to request reviewers. For this we are using a github app with pull request write permission (I need to request our app to be updated).
I will be making a following PR to merge the keys as we are using the same key for all the github classes.
The request feature is disabled by default.
Resolves #53

Added feature to request reviewers

---

.github/workflows/review-bot.yml
README.md

This PR has three changes:
1. Updated the README file to be more detailed on how to properly install the app with the request reviewers feature.
2. Updated the `repo-token` field to use the GitHub app which now has `pull-request` write permissions.
3. Enabled `request-reviewers` (won't trigger on this PR until it is merged).

Implement request reviewers on itself

---

action.yml
jest.config.js
src/github/pullRequest.ts
src/test/fellows.test.ts
src/test/github.test.ts
src/test/index.test.ts

Implemented the pagination method when fetching reviews, as the default endpoint has a hard limit of 30 results. By adding pagination we can go over the limit of 30.
Fixes #102

Added pagination 📑 for `listReviews` 👥 endpoint

---

src/runner.ts
src/test/runner/runner.test.ts

Added detailed explanation in the rules output, informing how each rule works and a list of approvals that counts towards incomplete rules (so we can see who's review count where).
Resolves #103
---
Example of rule output:
Details per rule:
<details><summary>Rule explanation</summary>Rule 'Basic' requires a given amount of reviews from users/teams 
For more info found out how the rules work in [Review-bot types](https://github.com/paritytech/review-bot#types)</details>
*   core-devs
*   gavofyork
<details><summary>Rule explanation</summary>Rule 'And Distinct' has many required reviewers/teams and requires all of them to be fulfilled **by different users**. 
The approval of one user that belongs to _two teams_ will count only towards one team. 
For more info found out how the rules work in …

Added more details in the rule output

---

action.yml
package.json
src/polkadot/fellows.ts

Added logic to search for a super identity in case that the user does not have an identity. 
If a super identity is found, this will be added to the array of address to fetch an identity from.
This fixes https://github.com/paritytech/review-bot/issues/107
Updated version to `2.3.1` as this is a small patch.

Fellows: Added search of super identity

---

README.md
action.yml
package.json
src/failures/fellowsRules.ts
src/github/types.ts
src/polkadot/fellows.ts
src/rules/types.ts
src/rules/validator.ts
src/runner.ts
src/test/fellows.test.ts
src/test/index.test.ts
src/test/rules/andDistinct.test.ts
src/test/rules/andRule.test.ts
src/test/rules/basicRule.test.ts
src/test/rules/config.test.ts
src/test/rules/fellows.test.ts
src/test/rules/or.test.ts
src/test/runner/conditions.test.ts
src/test/runner/runner.test.ts
src/test/runner/validation/and.test.ts
src/test/runner/validation/andDistinct.test.ts
src/test/runner/validation/fellows.test.ts
src/test/runner/validation/or.test.ts
src/util.ts
yarn.lock

Added new optional field to the config named `FellowScores` that has the score of each fellow per dan. It was done as an object (and not a collection) because it will never change in the foreseeable future (added up to dan IX).
When the rule of type `fellows` has the optional field of `minTotalScore` it will check that the score of the fellows who approved the PR sums up to that number. If it doesn't sum to that number it will fail with a custom error listing the score of each fellow for reference (and saying how many points are missing).
Added `FellowMissingScoreFailure` class which handles the formatting of errors when the score of fellows is not high enough.
This resolves #110
Downgraded JOI as there was a version mismatch that made the test fails.

Added required score grouping to fellows reviews

---

action.yml
package.json
src/polkadot/fellows.ts
yarn.lock

Fixed `Identity` object now being a tuple of type `[IdentityOf, BoundedVec]` introduced as as breaking change in v1.2.0
Fixes #118

Fix IdentityOf tuple introduced in v1.2.0

---

.github/workflows/github-issue-sync.yml
.github/workflows/javascript-test.yml
.github/workflows/publish.yml
.github/workflows/review-bot.yml
README.md

- Upgraded all actions to their latest versions
- No more `node 16 not supported` warnings
- Converted tests jobs into matrix
- It's more straightforward as it has a final job
- Updated `tibdex/github-app-token` to `actions/create-github-app-token`
- Done both in the docs as in the actions themselves.

Upgraded dependencies of actions

---

.github/workflows/github-issue-sync.yml
.github/workflows/javascript-test.yml
.github/workflows/publish.yml

This solves the problem that actions/cache was not working and removes all the warnings.

updated github actions to use latest major version
